// HORROR - STORMS
var horrorMovies = [
    "Psycho",
    "The Shining",
    "Halloween",
    "The Exorcist",
    "Rosemary's Baby",
    "Texas Chainsaw Massacre",
    "Night of the Living Dead",
    "Alien",
    "Get Out",
    "A Quiet Place",
    "Hereditary",
    "It Follows",
    "The Babadook",
    "Let the Right One In",
    "Candyman",
    "Scream",
    "The Blair Witch Project",
    "Paranormal Activity",
    "Don't Breathe",
    "The Conjuring",
    "Insidious",
    "Sinister",
    "A Nightmare on Elm Street",
    "The Ring",
    "The Others",
    "Jaws",
    "The Wicker Man",
    "The Witch",
    "The Sixth Sense",
    "28 Days Later",
    "The Descent",
    "Suspiria",
    "Midsommar",
    "Audition",
    "The Orphanage",
    "The Texas Chainsaw Massacre",
    "The Fly",
    "Carrie",
    "The Omen",
    "Poltergeist",
    "Pan's Labyrinth",
    "The Silence of the Lambs",
    "Evil Dead II",
    "The Babadook",
    "The Cabin in the Woods",
    "Tucker and Dale vs Evil",
    "Raw",
    "Train to Busan",
    "It",
    "Don't Look Now",
    "Re-Animator"
  ];

// DRAMA - RAIN
var dramaMovies = [
    "The Godfather",
    "Schindler's List",
    "The Shawshank Redemption",
    "Pulp Fiction",
    "Fight Club",
    "Forrest Gump",
    "Goodfellas",
    "The Dark Knight",
    "City of God",
    "The Departed",
    "The Green Mile",
    "Whiplash",
    "The Prestige",
    "12 Angry Men",
    "Casablanca",
    "The Godfather: Part II",
    "The Pianist",
    "American History X",
    "The Social Network",
    "The Silence of the Lambs",
    "American Beauty",
    "Scarface",
    "Gone with the Wind",
    "Gladiator",
    "Saving Private Ryan",
    "Braveheart",
    "No Country for Old Men",
    "The Revenant",
    "There Will Be Blood",
    "A Beautiful Mind",
    "Shutter Island",
    "Eternal Sunshine of the Spotless Mind",
    "The Wolf of Wall Street",
    "Birdman",
    "La La Land",
    "A Clockwork Orange",
    "Apocalypse Now",
    "Blade Runner",
    "Drive",
    "The Truman Show",
    "The Deer Hunter",
    "Into the Wild",
    "Million Dollar Baby",
    "The Grand Budapest Hotel",
    "Her",
    "The King's Speech",
    "Moonlight",
    "Manchester by the Sea",
    "Spotlight",
    "Dallas Buyers Club",
    "Moon",
    "Amélie"
  ];

// ADVENTURE MOVIES
var adventureMovies = [
    "The Lord of the Rings: The Fellowship of the Ring",
    "Indiana Jones and the Raiders of the Lost Ark",
    "Jurassic Park",
    "Star Wars: Episode IV - A New Hope",
    "The Lion King",
    "Avatar",
    "The Matrix",
    "Harry Potter and the Sorcerer's Stone",
    "The Hobbit: An Unexpected Journey",
    "The Avengers",
    "Back to the Future",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Guardians of the Galaxy",
    "The Dark Knight Rises",
    "Inception",
    "Interstellar",
    "The Princess Bride",
    "Raiders of the Lost Ark",
    "The Empire Strikes Back",
    "The Goonies",
    "The Wizard of Oz",
    "E.T. the Extra-Terrestrial",
    "Indiana Jones and the Last Crusade",
    "Toy Story",
    "The Incredibles",
    "The Jungle Book",
    "The Great Escape",
    "The Secret Life of Walter Mitty",
    "Life of Pi",
    "The Mummy",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    "Spider-Man: Into the Spider-Verse",
    "The Bourne Identity",
    "Mad Max: Fury Road",
    "The Princess Diaries",
    "Big Hero 6",
    "King Kong",
    "The Hunger Games",
    "The Lost World: Jurassic Park",
    "Captain America: The Winter Soldier",
    "Thor: Ragnarok",
    "Jumanji: Welcome to the Jungle",
    "The Land Before Time",
    "Alice in Wonderland",
    "Finding Nemo",
    "The NeverEnding Story",
    "National Treasure",
    "Men in Black",
    "Hugo",
    "The Odyssey",
    "Harry Potter and the Chamber of Secrets",
    "Star Wars: Episode VI - Return of the Jedi"
  ];

// FANTASY - SNOW
var fantasyMovies = [
    "The Wizard of Oz",
    "Harry Potter and the Philosopher's Stone",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    "The Lord of the Rings: The Two Towers",
    "Pan's Labyrinth",
    "Beauty and the Beast",
    "Stardust",
    "The Princess Bride",
    "Edward Scissorhands",
    "Coraline",
    "The NeverEnding Story",
    "Howl's Moving Castle",
    "Spirited Away",
    "The Dark Crystal",
    "Fantastic Beasts and Where to Find Them",
    "The Hobbit: An Unexpected Journey",
    "Alice in Wonderland",
    "Big Fish",
    "The Secret of Kells",
    "Time Bandits",
    "Willow",
    "Excalibur",
    "The Golden Voyage of Sinbad",
    "The Princess Diaries",
    "Maleficent",
    "The Spiderwick Chronicles",
    "Oz the Great and Powerful",
    "Labyrinth",
    "Ella Enchanted",
    "Clash of the Titans",
    "The Imaginarium of Doctor Parnassus",
    "Hook",
    "The NeverEnding Story II: The Next Chapter",
    "The BFG",
    "Jumanji: Welcome to the Jungle",
    "Legend",
    "Harry Potter and the Deathly Hallows: Part 2",
    "Harry Potter and the Goblet of Fire",
    "Harry Potter and the Prisoner of Azkaban",
    "Harry Potter and the Order of the Phoenix",
    "Harry Potter and the Half-Blood Prince",
    "The Lord of the Rings: The Return of the King",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "The Chronicles of Narnia: Prince Caspian",
    "The Chronicles of Narnia: The Voyage of the Dawn Treader",
    "Alice Through the Looking Glass",
    "Miss Peregrine's Home for Peculiar Children",
    "The Nutcracker and the Four Realms"
  ];

// ELSE WEATHER - COMEDY
var comedyMovies = [
    "Monty Python and the Holy Grail",
    "Airplane!",
    "Anchorman: The Legend of Ron Burgundy",
    "The Hangover",
    "Superbad",
    "Bridesmaids",
    "Step Brothers",
    "Dumb and Dumber",
    "Groundhog Day",
    "Shaun of the Dead",
    "Napoleon Dynamite",
    "The Big Lebowski",
    "Caddyshack",
    "Ferris Bueller's Day Off",
    "Ghostbusters",
    "Mean Girls",
    "The Princess Bride",
    "Back to the Future",
    "Annie Hall",
    "Tropic Thunder",
    "Hot Fuzz",
    "Zoolander",
    "Old School",
    "The Grand Budapest Hotel",
    "The Hangover Part II",
    "Office Space",
    "Austin Powers: International Man of Mystery",
    "Dodgeball: A True Underdog Story",
    "Wayne's World",
    "The 40-Year-Old Virgin",
    "This Is Spinal Tap",
    "Anchorman 2: The Legend Continues",
    "Meet the Parents",
    "The Naked Gun: From the Files of Police Squad!",
    "The Blues Brothers",
    "Wedding Crashers",
    "Elf",
    "The Producers",
    "Ace Ventura: Pet Detective",
    "Talladega Nights: The Ballad of Ricky Bobby",
    "Nacho Libre",
    "Zombieland",
    "Super Troopers",
    "Dazed and Confused",
    "Tommy Boy",
    "Clerks",
    "American Pie",
    "The Jerk",
    "Billy Madison",
    "Crazy, Stupid, Love.",
    "The Other Guys",
    "The Mask",
    "Groundhog Day",
    "Hot Shots!",
    "Meet the Fockers",
    "Tropic Thunder"
  ];